apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: elk
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: rishiray/springboot-app:${GIT_COMMIT}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: MONGODB_HOST
            value: "mongodb-1.mongodb"
          - name: MONGODB_PORT
            value: "27017"

